# Generated by Django 2.2.2 on 2019-08-05 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('last_date', models.DateField(default=datetime.date.today)),
                ('min_attendance', models.IntegerField(default=75)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seminfo.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lec_present', models.IntegerField(default=0)),
                ('lec_absent', models.IntegerField(default=0)),
                ('lec_cancelled', models.IntegerField(default=0)),
                ('attendance', models.FloatField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminfo.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('C', 'Cancelled'), ('0', 'Off')], default='0', max_length=1)),
                ('semester', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seminfo.Semester')),
                ('subject', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seminfo.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=3)),
                ('periods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='seminfo.Subject')),
                ('semester', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seminfo.Semester')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
