# Generated by Django 2.2.2 on 2019-08-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='periods',
        ),
        migrations.AddField(
            model_name='day',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='seminfo.Subject'),
        ),
    ]
