# Generated by Django 2.2.2 on 2019-08-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminfo', '0002_auto_20190805_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('lec_present', models.IntegerField(default=0)),
                ('lec_absent', models.IntegerField(default=0)),
                ('lec_cancelled', models.IntegerField(default=0)),
                ('attendance', models.FloatField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminfo.Semester')),
                ('subject', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seminfo.Subject')),
            ],
        ),
    ]
