# Generated by Django 2.2.2 on 2019-08-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminfo', '0003_subjectmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lec_needed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectmonth',
            name='lec_needed',
            field=models.IntegerField(default=0),
        ),
    ]
