# Generated by Django 2.2.2 on 2019-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminfo', '0005_auto_20190813_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='percentage_bar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectmonth',
            name='percentage_bar',
            field=models.IntegerField(default=0),
        ),
    ]
