# Generated by Django 2.2.2 on 2019-08-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminfo', '0006_auto_20190813_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='lec_needed',
            new_name='lec_to_skip',
        ),
        migrations.RenameField(
            model_name='subjectmonth',
            old_name='lec_needed',
            new_name='lec_to_skip',
        ),
    ]
